// ═══ src/lib/k6-config.ts — Generate k6 client config ═══

import { mkdirSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'
import type { Client, OnboardingStepResult } from './types'

const K6_CLIENTS_DIR = join(process.cwd(), 'k6', 'clients')

function ensureDir(dir: string) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
}

function generateConfig(client: Pick<Client, 'short_name' | 'name' | 'stack'>, prometheusUrl?: string, metricsKey?: string): string {
  const slug = client.short_name.toLowerCase().replace(/[^a-z0-9]/g, '-')
  const targetUrl = client.stack || `https://${slug}.example.com`

  return `// k6 config — ${client.name} (${slug})
// Auto-generated by Vantx onboarding
// Usage: k6 run k6/clients/${slug}.js

import http from 'k6/http';
import { check, sleep } from 'k6';
import { Rate, Trend } from 'k6/metrics';

const errorRate = new Rate('errors');
const latency = new Trend('request_latency', true);

export const options = {
  // ── Uptime check (runs every 1 min via cron) ──
  scenarios: {
    uptime: {
      executor: 'constant-arrival-rate',
      rate: 1,
      timeUnit: '1m',
      duration: '1m',
      preAllocatedVUs: 1,
      tags: { test_type: 'uptime' },
    },
    // ── Synthetic check (runs every 5 min via cron) ──
    synthetic: {
      executor: 'per-vu-iterations',
      vus: 1,
      iterations: 1,
      startTime: '0s',
      tags: { test_type: 'synthetic' },
    },
  },
  thresholds: {
    http_req_duration: ['p(95)<500', 'p(99)<1000'],
    errors: ['rate<0.01'],
    http_req_failed: ['rate<0.01'],
  },
${prometheusUrl && metricsKey ? `  // ── Remote write to Grafana Cloud ──
  ext: {
    loadimpact: {
      projectID: 0,
      name: '${slug}',
    },
  },
` : '  // Remote write: configure when Grafana Cloud keys are available\n'}};

const BASE_URL = '${targetUrl}';

// ── Uptime check ──
export function uptime() {
  const res = http.get(BASE_URL + '/');
  check(res, {
    'status is 200': (r) => r.status === 200,
    'response time < 500ms': (r) => r.timings.duration < 500,
  });
  errorRate.add(res.status !== 200);
  latency.add(res.timings.duration);
}

// ── Synthetic user flow ──
export function synthetic() {
  const pages = ['/', '/api/health'];

  for (const page of pages) {
    const res = http.get(BASE_URL + page);
    check(res, {
      [\`\${page} status 2xx\`]: (r) => r.status >= 200 && r.status < 300,
      [\`\${page} latency < 1s\`]: (r) => r.timings.duration < 1000,
    });
    errorRate.add(res.status >= 400);
    latency.add(res.timings.duration);
    sleep(1);
  }
}

// ── Load test scenario (manual, not in cron) ──
// Run: k6 run --tag test_type=load -e SCENARIO=load k6/clients/${slug}.js
export function load() {
  const res = http.get(BASE_URL + '/');
  check(res, {
    'status is 200': (r) => r.status === 200,
  });
  errorRate.add(res.status !== 200);
  latency.add(res.timings.duration);
  sleep(0.5);
}

export default function () {
  const scenario = __ENV.SCENARIO || 'uptime';
  if (scenario === 'load') load();
  else if (scenario === 'synthetic') synthetic();
  else uptime();
}
`
}

export function generateK6Config(
  client: Pick<Client, 'short_name' | 'name' | 'stack'>,
  prometheusUrl?: string,
  metricsKey?: string,
): OnboardingStepResult {
  const slug = client.short_name.toLowerCase().replace(/[^a-z0-9]/g, '-')
  const filePath = join(K6_CLIENTS_DIR, `${slug}.js`)

  try {
    ensureDir(K6_CLIENTS_DIR)
    const content = generateConfig(client, prometheusUrl, metricsKey)
    writeFileSync(filePath, content, 'utf-8')
    return {
      step: 'k6-config',
      status: 'success',
      message: `k6 config created: k6/clients/${slug}.js`,
      data: { filePath, slug },
    }
  } catch (err) {
    return { step: 'k6-config', status: 'failed', message: String(err) }
  }
}
