[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/portal"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
enable_confirmations = false

[analytics]
enabled = false
